version: "3"

services:
  minio:
    image: minio/minio:latest
    ports: 
      - "${FAKE_S3_SERVER_PORT}:${FAKE_S3_SERVER_PORT}"
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    volumes:
      - ./volume/minio:/data
    command: server --address 0.0.0.0:${FAKE_S3_SERVER_PORT} /data
  
  gcs:
    image: fsouza/fake-gcs-server
    volumes:
      - ./volume/gcs/${FAKE_GCS_SERVER_BUCKET_NAME}:/data
      - ./volume/gcs/storage:/storage
    command:
      - -host=0.0.0.0
      - -port=${FAKE_GCS_SERVER_PORT}
      - -scheme=http